### ISSUE TITLE
Set location

### ISSUE THREAD

**Issue by nicholasswanson** [ResistanceCalendar/design#16]
**Home screen**
<img width="320" src="https://cloud.githubusercontent.com/assets/3856906/23735166/e1815838-0438-11e7-9d2a-b3721928fc23.png">

**Set location screen**
<img width="320" src="https://cloud.githubusercontent.com/assets/3856906/23735063/32a1db08-0438-11e7-987a-2d5a1e11a29e.png">

**Two variants on home screen**
<img width="270" alt="screen shot 2017-03-08 at 7 46 17 pm" src="https://cloud.githubusercontent.com/assets/3856906/23735033/00a8caee-0438-11e7-9629-5d445bce3201.png">

**Comment by InciteDemocracy** [comment]
What about the option of using popup menus for setting date and location? It has been suggested that people don't like it when their data/content goes away completely. A pop up (or drop down or any other variation) that mostly covers the events list would allow them to "stay" where they are but change the settings quickly and return to a refreshed list. Could something like this work?: 

![screenshot 2017-03-08 20 10 22](https://cloud.githubusercontent.com/assets/25624431/23738175/95625fee-043b-11e7-9672-e0818efcc5e6.png)

**Comment by dentemple** [comment]
I definitely like the idea of having a modeless window for filtering options.

**Comment by InciteDemocracy** [comment]
Yes, this way we should be able to use the same menu selection components for both desktop and mobile.

**Comment by bripenney** [comment]
![home](https://cloud.githubusercontent.com/assets/24579735/23837011/4d159910-074f-11e7-88e1-cbe25c3623e7.png)
Some thoughts on this. For logo/color comments I'll upload elsewhere. This is primarily for the layout on this page.

**Comment by nicholasswanson** [comment]
Latest from @InciteDemocracy is on [Trello](https://trello.com/c/RH2aFEmK/94-a-user-sets-the-location).
