### ISSUE TITLE
Single Event Page

### ISSUE THREAD

**Issue by bripenney** [ResistanceCalendar/design#18]
![screenshot_2017-03-09_21 39 25](https://cloud.githubusercontent.com/assets/24579735/23837480/16e722ca-0757-11e7-8bbc-379130a62583.png)
![single_event](https://cloud.githubusercontent.com/assets/24579735/23837564/645efd56-0758-11e7-92d5-9ffadc196643.png)

Took a shot at this page. Our primary action we want the user to take is to rsvp, so I think that should be pretty prominent. For the back button, since this isn't a mobile app does it make sense to have a back button in that style?

If we want people to be able to look at events with super low lift, perhaps a popup would be more useful. If users are navigated to an entirely new page every time they click on an event, when they go back will all of their search filters etc remain the same?

**Comment by nicholasswanson** [comment]
Latest on [Trello](https://trello.com/c/TYv5MDpA/92-a-user-views-the-event-details-page) from @InciteDemocracy.

Uploading to show my basic thinking on it.
<img width="323" src="https://cloud.githubusercontent.com/assets/3856906/23979941/e420d6d2-09b9-11e7-815b-8faab7cbcdb4.png">
