### ISSUE TITLE
Search UX

### ISSUE THREAD

**Issue by nicholasswanson** [ResistanceCalendar/design#2]
* Auto-suggest functionality will be added for MVP
* Can search for tags, cities, states
* “Jump to” dates and move between

**Comment by nicholasswanson** [comment]
Key points:
* Separating date and search terms
* Tapping a tag or searching and selecting from autosuggest (or simply hitting enter) would take to search results page
* Tapping the date would open a modal (full screen on mobile) to select from 30-day calendar view, with quick arrows to jump month, and probably "Today" link for reset

Open questions
* Use the "near me" functionality? I could see a simple modal to interact with
* Do we get any sort of data with the tags? Would be nice to include some indication of tag type (location v issue) or "quality" (number of events tagged)

## Default view from mobile
<img width="319" src="https://cloud.githubusercontent.com/assets/3856906/23691128/7a10eafa-037b-11e7-8718-60596817d1cd.png">

## Search input variants
<img width="559" alt="screen shot 2017-03-07 at 9 11 57 pm" src="https://cloud.githubusercontent.com/assets/3856906/23691159/a1a85b5c-037b-11e7-99ed-0db727d129e0.png">

## Location - simple
<img width="214" src="https://cloud.githubusercontent.com/assets/3856906/23691071/355763e4-037b-11e7-8c05-eb65ff19c215.png">

**Comment by InciteDemocracy** [comment]
This drop-down looks amazing, not sure if we will be able to include it in the MVP. I like the middle example that shows icons to differentiate between tag types.

**Comment by nicholasswanson** [comment]
Branched the location discussion into #16.

For basic search, should be pretty straightforward for input:

<img width="539" alt="screen shot 2017-03-08 at 7 57 33 pm" src="https://cloud.githubusercontent.com/assets/3856906/23735309/a2731c3e-0439-11e7-97ff-4af21f4dfcc0.png">

Not sure if I'm missing anything, maybe that's it for the search UX/UI for now? List items shouldn't change, only filter.

**Comment by bripenney** [comment]
@nicholasswanson are you looking to do more of a Material Design simple look for the MVP or is this your vision for the entire future?

**Comment by bripenney** [comment]
For search, it might be interesting to be able to search by popularity too. I don't know what the capabilities are with the data being sourced from Facebook, but if I know 2000 people in Austin are going to the same event as me that might push me to participate more.

**Comment by nicholasswanson** [comment]
@bripenney Let's create a new issue around this not tied to 1.0. I think there is quite a bit we could explore here, but 1.0 is limiting.
