### ISSUE TITLE
Tags UX

### ISSUE THREAD

**Issue by nicholasswanson** [ResistanceCalendar/design#4]
<img width="354" alt="screen shot 2017-03-02 at 9 11 01 pm" src="https://cloud.githubusercontent.com/assets/3856906/23538991/c67932a0-ff8c-11e6-888b-a26ad59c5722.png">

* How does interacting with a tag affect the search experience?
* How do we surface these?
* Should we promote tags that have good results or are trending?

**Comment by nicholasswanson** [comment]
## Proposed
When tapping, takes to search results page.

**List**
<img width="340" src="https://cloud.githubusercontent.com/assets/3856906/23690649/421d3336-0378-11e7-996b-b849ef8d67e3.png">

**Event details**
<img width="340" src="https://cloud.githubusercontent.com/assets/3856906/23690700/93bd0914-0378-11e7-931c-96f6ebb73142.png">

**Comment by InciteDemocracy** [comment]
There are some technical implications to tags. Currently tags are added to events manually and they may not be part of the stripped down MVP. If we want to add them we will need to build a way to manually tag events or add them automatically by pulling keywords from the event title/description. For now I think it makes sense to strip them out of the UX.

**Comment by nicholasswanson** [comment]
Got it. Updated list items, removed altogether in event details.

<img width="333" alt="screen shot 2017-03-08 at 6 43 45 pm" src="https://cloud.githubusercontent.com/assets/3856906/23733690/30c44d06-042f-11e7-989e-8cd51e6b626f.png">
