### ISSUE TITLE
Menu and navigation IA

### ISSUE THREAD

**Issue by nicholasswanson** [ResistanceCalendar/design#5]
Just need to think more about whether we really need a menu, if the hierarchy is right.

**Comment by nicholasswanson** [comment]
@InciteDemocracy (Devin) What do you think about tweaking the menu, especially for mobile? Seems a shame to hide only two items behind an icon, I would recommend either exposing the primary action (Submit event) or, if we have more core nav items we want to include, adding those.
 
![img_7962](https://cloud.githubusercontent.com/assets/3856906/23589900/095931ec-018b-11e7-8e58-b75b3382231b.jpg)

**Comment by InciteDemocracy** [comment]
I'm in full agreement! If we can find a better home for the other actions we could err on the side of making event submissions more prominent and accessible (option 1). If that's the best  place for them all to live, then having 4-5 in there helps to justify the menu. (option 2) Your call.

**Comment by nicholasswanson** [comment]
For now, recommending option 1:

<img width="338" alt="screen shot 2017-03-07 at 9 22 19 pm" src="https://cloud.githubusercontent.com/assets/3856906/23691258/3cc27028-037c-11e7-8545-449536a53dae.png">

**Comment by InciteDemocracy** [comment]
and the other stuff goes in the footer?

**Comment by nicholasswanson** [comment]
@InciteDemocracy Yes, that being social accounts and privacy.

**Comment by InciteDemocracy** [comment]
Yep, that works!
