### ISSUE TITLE
Footer content

### ISSUE THREAD

**Issue by nicholasswanson** [ResistanceCalendar/design#6]
Creating layout for basic info (©, social) and also pushes for terms, privacy, about.

**Comment by nicholasswanson** [comment]
@InciteDemocracy (Devin) Do we have terms and privacy statements to add here? Just worried about legal implications if we get a big rush of folks.

**Comment by InciteDemocracy** [comment]
It used to say "all rights reserved depending on our mood" but I removed it altogether. 

I think something like this will work ok for a privacy policy, I will ask #legal for input as well:

##  **Use of Information** 
Any personal information you provide to the team of volunteers who run The Resistance Calendar is maintained and accessible only by us. We use aggregate data to monitor website traffic. No personally identifiable information is disclosed in this process; only general information in aggregate form. From time to time, we may use your email to inform you of changes and enhancements to The Resistance Calendar. We will NOT release your personal information to other organizations without your express permission. Any modifications to this policy will be posted in this space. We welcome any questions or comments you have.

**Comment by nicholasswanson** [comment]
Created #13 to address the privacy policy.

Suggested layout for footer below (mobile view). Basic, and we could use multiple columns for desktop, but should include everything we need for now.

<img src="https://cloud.githubusercontent.com/assets/3856906/23690085/cdea331e-0373-11e7-9479-b4bb38ec5c4b.png">

**Comment by nicholasswanson** [comment]
Should we consider adding a link for ProgCode? "Part of ProgCode network" or something like that, as a way to pay it forward? Just a thought.

**Comment by InciteDemocracy** [comment]
If I am not mistaken, Prog_code doesn't want to attract any trolls and is happier to remain in the shadows.

**Comment by nicholasswanson** [comment]
Ha, understandable.
