### ISSUE TITLE
Home page "hero" improvements

### ISSUE THREAD

**Issue by nicholasswanson** [ResistanceCalendar/design#7]
Lots of flexibility here, from trying to improve to removing altogether and getting into the calendar.

**Comment by nicholasswanson** [comment]
I suggest that we do keep the header, but focus on communicating the mission of the site, and getting right into the product from there. Example (mobile):

<img src="https://cloud.githubusercontent.com/assets/3856906/23689998/2e6a4bbc-0373-11e7-93f7-c66962a9b288.png">

**Comment by dentemple** [comment]
Oh, yeah, something like this would definitely feel more engaging than just a colored header.

**Comment by InciteDemocracy** [comment]
I'm open to both options. Removing it altogether and compressing it into a small logo/header would let people get straight to the "meat" of the site. Something like this is cool too. I'm guessing that users returning to the site would rather go straight to content rather than see a big banner on multiple visits. There is no reason why we shouldn't make this improvement to the webflow/tockify site right away.

**Comment by bripenney** [comment]
What about this kind of style?
<img width="727" alt="screen shot 2017-03-09 at 11 00 23 pm" src="https://cloud.githubusercontent.com/assets/24579735/23782735/331fe284-051c-11e7-8aa8-d596d11d3554.png">

So logo would be at the top of site with nav, then a statement with image below. (Copy improvised)

I do think @InciteDemocracy has a point about getting straight to the content though. Maybe this moves to an about page in the future. Perhaps the home page could feature full width featured events at the top, then the list format below with search, filters, etc.

**Comment by dentemple** [comment]
Perhaps only a half-size option for the landing page?  (Or whichever percentage would be best).

The top x% of the page would be this picture banner, the bottom x% would the main options (such as filtering or adding events) that we want users to be able to jump to, and then we can have all of the rest of the pages just stick to using either a navbar alone or use a navbar with a minimal top banner.

**Comment by bripenney** [comment]
The more I'm thinking about it... does it make sense to have a hero image at all? I think we need an about page that explains our intentions with the Resistance Calendar, the partnership with Michael Moore, etc. That page could be more image heavy while the home page could be an immediate tool. Just a thought.

**Comment by nicholasswanson** [comment]
For people who are landing on the home page, for the first time (or even returning after a period), it seems useful to have a way to set context before jumping to events. If we have can follow on with a way to jump returning users straight to the events, that seems like a nice to have.

**Comment by nicholasswanson** [comment]
I'll recommend we use a simple header with text for now, if we can achieve a great photo background by launch let's address then.
