### ISSUE TITLE
Home page email section

### ISSUE THREAD

**Issue by nicholasswanson** [ResistanceCalendar/design#8]
* Want to keep this section?
* If so, what is our strategy for collecting/utilizing emails?

**Comment by nicholasswanson** [comment]
I do think this _can_ have value, but I'm not sure how we see it. Would be a shame not to have it for launch, but I want to make sure we communicate how we will use email addresses and the benefit to the user.

cc @InciteDemocracy

**Comment by InciteDemocracy** [comment]
The main value of collecting emails initially was to be able to let people know when we have made a significant update. But overall, I don't think we care much about collecting them. IMO this aspect of the project can be minimized or phased out completely.

**Comment by nicholasswanson** [comment]
Great, I will recommend that we axe it until we have a good story, at which point we could re-introduce.
